---
abstract: 'Evaluate code with App::EvalServer'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-Eval
no_index:
  directory:
    - t
    - utils
requires:
  POE::Component::IRC: 6.36
  POE::Component::IRC::Plugin::BotCommand: 0
  POE::Filter::JSON: 0
  POE::Session: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.008
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Component-IRC-Plugin-Eval
  homepage: http://search.cpan.org/dist/POE-Component-IRC-Plugin-Eval/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/poe-component-irc-plugin-eval.git
version: 0.05
x_authority: cpan:HINRIK
